core/urls.py
from django.urls import path

from .import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('customer/<uuid:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/create', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customer/update/<uuid:pk>',views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/delete/<uuid:pk>',views.CustomerDeleteView.as_view(), name='customer-delete'),
]

core_api/urls.py
from rest_framework import routers 
from django.urls import path

from . import views

urlpatterns = [
    path('customers/', views.CustomerList.as_view()),
    path('customers/<uuid:pk>', views.CustomerDetail.as_view()),
    path('payments/', views.PaymentList.as_view()),
    path('payments/<uuid:pk>', views.PaymentDetail.as_view()),
]

login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name="register"),
]

payapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('login/', include('login.urls')),
    path('api/', include('core_api.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
import random
import uuid
from django.db import models
from django.db.models.signals import post_save


class Customer(models.Model):
    """A model for Customer table"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    paternal_surname = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)

    def __str__(self):
        return self.name


class PaymentsCustomer(models.Model):
    """A model for Payments Table"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    product_name = models.CharField(max_length=100)
    quantity = models.IntegerField()
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return self.product_name


def create_dummy_payments_signal(sender, instance, **kwargs):
    payments_count = random.randint(1, 9)
    customer = instance

    for payment in range(0, payments_count):
        random_amount = random.randint(20, 5000)
        random_quantity = random.randint(1,20)

        PaymentsCustomer.objects.create(
            product_name=f"Pago {payment}",
            amount=random_amount,
            quantity=random_quantity,
            customer=customer
        )

post_save.connect(create_dummy_payments_signal, sender=Customer)

core_api/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    """For for handling user registration"""

    email = forms.EmailField(required=True)
    is_super_administrator = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse

from .models import Customer

class HomeView(TemplateView):
    """View for Home"""

    template_name = 'home.html'


class IndexView(LoginRequiredMixin, ListView):
    """View for index"""

    template_name = "index.html"
    model = Customer
    login_url = '/login/'


class CustomerDetailView(LoginRequiredMixin, DetailView):
    """View for Customer Details"""

    template_name = "customer-detail.html"
    model = Customer
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer_id = self.kwargs['pk']
        context["payments"] = Customer.objects.get(pk=customer_id).paymentscustomer_set.all()
        return context


class CustomerCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """View for creating Customers"""

    permission_required = 'core.add_customer'

    template_name = 'customer/customer-create.html'
    model = Customer
    fields = ['name', 'paternal_surname', 'email']
    success_url = '/index/'


class CustomerUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """View for editing Customers"""

    permission_required = 'core.change_customer'

    template_name = 'customer/customer-edit.html'
    model = Customer
    fields = ['name', 'paternal_surname', 'email']
    success_url = '/index/'


class CustomerDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """View for deleting Customer"""

    permission_required = 'core.delete_customer'

    template_name = 'customer/customer-delete.html'
    model = Customer
    success_url = '/index/'

core_api/views.py
from rest_framework import generics

from core.models import Customer, PaymentsCustomer
from . import serializers


class CustomerList(generics.ListCreateAPIView):
    queryset = Customer.objects.all()
    serializer_class = serializers.CustomerSerializer


class CustomerDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Customer.objects.all()
    serializer_class = serializers.CustomerSerializer


class PaymentList(generics.ListCreateAPIView):
    queryset = PaymentsCustomer.objects.all()
    serializer_class = serializers.PaymentsSerializer


class PaymentDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = PaymentsCustomer.objects.all()
    serializer_class = serializers.PaymentsSerializer

login/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

from .forms import RegistrationForm
from . import permissions


def login_view(request):
    """View for Login User"""

    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            messages.info(request, f"Iniciaste sesión como {username}")
            return redirect('index')

        else:
            print("Usuario es None")
            login_form = AuthenticationForm()
            messages.error(request, "Usuario o contraseña erróneo")
            context = {}
            context['form'] = login_form
            return render(request, 'login.html', context)

    else:
        login_form = AuthenticationForm()
        context = {}
        context['form'] = login_form
        return render(request, 'login.html', context)


def logout_view(request):
    logout(request)
    return redirect('home')


def register_view(request):
    """View for Login User"""

    if request.user.is_authenticated:
        return redirect('index')

    if request.method == "POST":

        form = RegistrationForm(request.POST)

        if form.is_valid():
            user = form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            is_super_administrator = form.cleaned_data['is_super_administrator']

            print(is_super_administrator)

            user = authenticate(username=username, password=password)
#
            if is_super_administrator:
                permissions.set_user_as_super_administrator(user)
#
            login(request, user)
            messages.success(request, "Registro exitoso")
#
            return redirect("index")

        messages.error(request, "Error en registro. Información inválida")
        return redirect('register')

    else:
        form = RegistrationForm()

        context = {}
        context['form'] = form
        return render(request, 'register.html', context)

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Tailwind -->
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Test API</title>
</head>
<body>

    <div class="container flex items-center justify-between h-full px-6 mx-auto text-purple-600 dark:text-purple-300">
            <ul class="flex justify-end items-center flex-shrink-0 space-x-6">

                {% if user.is_authenticated %}
                    <li>
                        <a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                            href="/"><svg class="w-4 h-4 mr-3" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                                <path d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                            </svg> <span>{{ user }}</span></a>
                    </li>
                    <li>
                        <a  class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                            href="{% url 'logout' %}">
                            <i class="fa-solid fa-right-from-bracket"></i>
                            <span> Log out</span>
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                            href="/">
                            </svg> <span>Registrarse</span></a>
                    </li>
                    <li>
                        <a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200"
                            href="{% url 'login' %}">
                            <i class="fa-solid fa-right-from-bracket"></i>
                            <span>Inicia Sesión</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    
    {% block main_content %}
    {% endblock %}
</body>
</html>

core/templates/customer-detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block main_content %}

<div class="container grid px-6 mx-auto">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
        Pagos de {{ object.name }} {{ object.paternal_surname }}
    </h2>



    <h4 class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300">
        <a href="{% url 'index' %}">
            <i class="fa-sharp fa-solid fa-arrow-left"></i>
            Atras
        </a>
    </h4>
    <h4 class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300">Descripción</h4>
    <div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
        <div class="w-full overflow-x-auto">
            <table class="w-full whitespace-no-wrap">
                <thead>
                    <tr
                        class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                        <th class="px-4 py-3">Producto</th>
                        <th class="px-4 py-3">Costo</th>
                        <th class="px-4 py-3">Cantidad</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">

                {% if payments %}
                    {% for payment in payments %}
                        <tr class="text-gray-700 dark:text-gray-400">
                            <td class="px-4 py-3">
                                <div class="flex items-center text-sm">

                                    <div>
                                        <p class="font-semibold">{{ payment.product_name }}</p>
                                    </div>
                                </div>
                            </td>
                            <td class="px-4 py-3 text-sm">$ {{ payment.amount|intcomma }}</td>
                            <td class="px-4 py-3 text-xs">{{ payment.quantity }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                        <h1 class="text-6xl font-semibold text-gray-700 dark:text-gray-200">Este cliente no tiene pagos por el momento</h1>
                {% endif %}
                    
                </tbody>
            </table>
        </div>

    </div>
    </div>
</div>

{% endblock %}

core/templates/customer/customer-create.html
{% extends 'base.html' %}

{% block main_content %}
    <h1>Crear un Customer</h1>

    <div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <form method="POST">
            {% csrf_token %}

            {% for field in form %}
                    <label class="block text-sm">
                        <span class="text-gray-700 dark:text-gray-400">{{ field.label_tag }}</span>
                        {{ field }}
                    </label>
                    <br>
            {% endfor %}

            <button 
                class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" 
                type="submit">
                Submit
            </button>
        </form>

{% endblock %}

core/templates/customer/customer-delete.html
{% extends 'base.html' %}

{% block main_content %}
    <h1>Borrar {{ object }}</h1>

    <form method="post">{% csrf_token %}
        <p>¿Estás seguro de que deseas eliminar "{{ object }}"?</p>
            {{ form }}
        <button
            class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
            type="submit">
            Submit
        </button>
    </form>

{% endblock %}

core/templates/customer/customer-edit.html
{% extends 'base.html' %}

{% block main_content %}
<h1>Crear un Customer</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button
        class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
        type="submit">
        Submit
    </button>
</form>

{% endblock %}

core/templates/home.html
{% extends 'base.html' %}

{% block main_content %}

    <div class="max-w-2xl px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <p class="mb-4 text-gray-600 dark:text-gray-400">
            <strong>Bienvenido a PayAPI</strong>
        </p>
        <p class="mb-4 text-gray-600 dark:text-gray-400">
            <strong>Favor de Iniciar Sesión</strong>
        </p>
    </div>

    <a
        href="{% url 'login' %}"
        class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
        Iniciar Sesión
    </a>
    <a  
        href="{% url 'register' %}"
        class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
        Registrarse
    </a>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}

{% block main_content %}
    <div class="container px-6 mx-auto grid">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Tus Clientes</h2>

            {% if perms.core.add_customer %}
                <a class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
                    href="{% url 'customer-create' %}">
                    <div class="flex items-center">
                        <span>Crear nuevo Cliente</span>
                    </div> 
                </a>
            {% endif %}

        <!-- Widgets -->

        <!-- Table -->
        <div class="w-full overflow-hidden rounded-lg shadow-xs">
            <div class="w-full overflow-x-auto">
                <table class="w-full whitespace-no-wrap">
                    <thead>
                        <tr
                            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                            <th class="px-4 py-3">Cliente</th>
                            <th class="px-4 py-3">Amount</th>
                            {% if perms.core.change_customer %}
                                <th class="px-4 py-3">Editar</th>
                            {% endif %}

                            {% if perms.core.delete_customer %}
                                <th class="px-4 py-3">Eliminar</th>
                            {% endif %}
                        </tr>
                    </thead>

                    {% if customer_list %}
                        {% for customer in customer_list %}
                            <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                                <tr class="text-gray-700 dark:text-gray-400">
                                    <td class="px-4 py-3">
                                        <div class="flex items-center text-sm">
                                            <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block"><img
                                                    class="object-cover w-full h-full rounded-full"
                                                    src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixlib=rb-1.2.1&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=200&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjE3Nzg0fQ"
                                                    alt="" loading="lazy">
                                                <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                                            </div>
                                            <div>
                                                <a href="{% url 'customer-detail' customer.id %}">
                                                    <p class="font-semibold">{{ customer.name }}</p>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="px-4 py-3 text-sm">$ 863.45</td>

                                    {% if perms.core.change_customer %}
                                        <td class="px-4 py-3 text-xs">
                                            <button
                                            class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
                                            aria-label="Like">
                                                <a href="{% url 'customer-update' customer.id %}">
                                                    Editar
                                                    <i class="fa-solid fa-pen"></i>
                                                </a>
                                                </a>
                                            </button>
                                        </td>
                                    {% endif %}

                                    {% if perms.core.delete_customer %}
                                        <td class="px-4 py-3 text-sm">
                                            <button
                                                class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
                                                aria-label="Like">
                                                <a href="{% url 'customer-delete' customer.id %}">
                                                Eliminar
                                                <i class="fa-solid fa-eraser"></i>
                                            </a>
                                            </button>
                                        </td>
                                    {% endif %}
                                </tr>
                            </tbody>
                        {% endfor %}
                    {% endif %}
                </table>
            </div>
        </div>
{% endblock %}

login/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    {% load crispy_forms_tags %}
    <h1>Login View</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Login</button>
    </form>

    {% if messages %}
        {{ messages.error }}
    {% endif %}

    <p>Si no tienes cuenta, <a href="{% url 'register' %}">registrate aquí</a></p>
</body>
</html>

login/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% load crispy_forms_tags %}
    <h1>Register Form</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">SignUp</button>
    </form>
    
</body>
</html>